### ISSUE TITLE
A question about the sampling method

### ISSUE THREAD

**Issue by yurunsheng1** [longhoangphi225/MultiSample-Hypernetworks#2]
Hi @longhoangphi225,

Thank you for your excellent code!  It really helps me a lot!

I have a question regarding the sampling method. In your paper (line 2-5 of Algorithm 1, https://arxiv.org/pdf/2212.01130.pdf), 
partition sampling is only used when J (the number of objectives) is large than 2; otherwise the Dir sampling is used.

But it seems that in your code, when J=2, the sampling method is uniform, [https://github.com/longhoangphi225/MultiSample-Hypernetworks/blob/main/Toy_Examples/MH_1.ipynb](url)

```
for i in range(n_mo_sol):
      random = np.random.uniform(start, end)
      #random = np.random.uniform(start + i*(end-start)/head, start+ (i+1)*(end-start)/head)
      ray = np.array([np.cos(random),
                        np.sin(random)], dtype='float32')
```
while  J>2, the sampling method seems to be a combination of Dirichlet and partition sampling? https://github.com/longhoangphi225/MultiSample-Hypernetworks/blob/main/Toy_Examples/MH_4.ipynb
```
  test_rays = get_reference_directions("das-dennis", 3, n_partitions=5).astype(
        np.float32
    )

for j in range(n_mo_sol):
      ray = np.random.dirichlet([1/3]*3, 1).astype(np.float32)
      ray = ray@test_rays[partition[j]]
      ray /= np.sum(ray)
      ray = ray.astype(np.float32)
      rays.append(torch.from_numpy(
                      ray.flatten()
                  ).to(device))  
```

Are these typos?

Also, I am wondering whether you could give me some explainations on  ``` ray = ray@test_rays[partition[j]]```, why sampling from  dirichlet needs to be multiplied by partition sampling? 

Thanks so much in advance!

**Comment by longhoangphi225** [comment]
Hi,

I am sorry for my late response.
In this case, `test_rays[partition[j]]` is vectors creating a partition. In
the meanwhile, ***@***.***_rays[partition[j]]` is the convex combination of
vectors creating the j-th partition. Therefore, ***@***.***_rays[partition[j]]`
helps us sample a random vector in the j-th partition. Does that make sense?

I am so delighted to learn that my work is useful to you. I and my research
are very welcome to discuss and collaborate with other researchers like
you. Could you share more about yourself, and your current research?

Best Regards,
Long

**Comment by yurunsheng1** [comment]
Hi Long,

Thank you for addressing my concern. Your response is very helpful.

I have already connected you via LinkedIn and we may continue our discussion there.

Best regards, 
Runsheng
